server {
    listen 80 default_server;
    server_name dmz-web.lab.local;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        add_header X-Zone "DMZ" always;
        add_header X-Lab "network-seg-lab" always;
    }

    location /health {
        return 200 '{"status":"ok","zone":"dmz","host":"nginx-dmz"}';
        add_header Content-Type application/json;
    }

    access_log /var/log/nginx/access.log combined;
    error_log  /var/log/nginx/error.log warn;
}
